'''
This python file will be used to answer the questions 
14 to 23 
made for the SQL Challenge,
the task will be presente as a comment and bellow its respective code,
the answer will be generated by running the code.
'''

from csv import list_dialects
from os import confstr_names
import sqlite3
from threading import local

conn = sqlite3.connect('cocktails_database.sqlite')
c = conn.cursor()


# Task 14: which restaurants offer cocktails with ID 8 or ID 11?

c.execute('''
SELECT local.lname
FROM local
WHERE local.lid IN (
    SELECT cocktail_local.lid
    FROM cocktail_local
    WHERE cocktail_local.cid=8 OR cocktail_local.cid=11
    )
''')
rest_cock_8or11= c.fetchall()
rest_cock_8or11 = [x[0] for x in rest_cock_8or11]
print("Task 14:\nThis are the restaurants that offer the cocktails with the ID 8 or 11: "+(', '.join(rest_cock_8or11)))

# Task 15: Which cocktail is alcoholic and is served in the 'cocktailglas'?

c.execute('''
SELECT cocktail.cname
FROM cocktail
WHERE cocktail.alkoholisch='y' AND cocktail.gid IN (
    SELECT glas.gid
    FROM glas
    WHERE glas.gname='Cocktailglas'
    )
''')
cockglas_alco= c.fetchall()
cockglas_alco = [x[0] for x in cockglas_alco]
print("\nTask 15:\nThis are the cocktails that are alcoholic and are served in the Cocktail Glass: "+(', '.join(cockglas_alco)))

# Task 16: Which glasses are never used?

c.execute('''
SELECT glas.gname 
FROM glas 
WHERE glas.gid NOT IN (
    SELECT cocktail.gid 
    FROM cocktail)
''')
g_not_used= c.fetchall()
g_not_used = [x[0] for x in g_not_used]
print("\nTask 16:\nThis are the glasses that are never used in any cocktail: "+(', '.join(g_not_used)))

# Task 17: which cocktails do you talk about (table COCKTAIL _PERSON)? Output the names of the cocktails!
 
c.execute('''
SELECT cocktail.cname 
FROM cocktail 
WHERE cocktail.cid IN (
    SELECT Cocktail_person.cid 
    FROM Cocktail_person)
''')
talk_cocktails= c.fetchall()
talk_cocktails = [x[0] for x in talk_cocktails]
print("\nTask 17:\nThis are the cocktails that are talked about: "+(', '.join(talk_cocktails)))

# Task 18: Which ingredients have an alcohol content between 0 and 50?

c.execute('''
SELECT ingredient.zname 
FROM ingredient 
WHERE ingredient.alkoholgehalt BETWEEN 0 AND 50
''')
ing_alcohol= c.fetchall()
ing_alcohol = [x[0] for x in ing_alcohol]
print("\nTask 18:\nThis are the ingredients that have an alcohol content between 0 and 50 according to the table Ingredients (not My_Ingredientes): "+(', '.join(ing_alcohol)))

# Task 19: What personal names begin with S?

c.execute('''
SELECT person.name 
FROM person 
WHERE person.name LIKE 'S%'
''')
name_s= c.fetchall()
name_s = [x[0] for x in name_s]
print("\nTask 19:\nThis are the personal names begin with S: "+(', '.join(name_s)))

# Task 20: Is there a place that doesn't serve cocktails?

c.execute('''
SELECT IFNULL (max('All places serve cocktails.'), 'Some places do not serve any cocktails.')
FROM  Cocktail_local
WHERE Cocktail_local.lid IN (
    SELECT local.lid
    FROM local
)
''')
if_local_serves_cocktails= c.fetchall()
if_local_serves_cocktails = [x[0] for x in if_local_serves_cocktails]
print("\nTask 20:\n"+(', '.join(if_local_serves_cocktails)))

# Task 21: How many ingredients are there?

c.execute('''
SELECT COUNT(DISTINCT ingredient.zid) 
FROM ingredient
''') #counting all rows except null or duplicates
count_ing= c.fetchall()
count_ing = [x[0] for x in count_ing]
print("\nTask 21:\nThere are "+(str(count_ing)[1:-1])+" ingredients in total.")

# Task 22: What is the average alcohol content of the ingredients?

c.execute('''
SELECT avg(ingredient.alkoholgehalt) 
FROM ingredient
''')
avg_alcohol= c.fetchall()
avg_alcohol = avg_alcohol[0][0]
avg_alcohol_rounded = round(float(avg_alcohol))
print(f"\nTask 22:\nThere average of alcohol content of the ingredients is {avg_alcohol}, or {avg_alcohol_rounded} if rounded up, according to the table Ingredients (not My_Ingredientes)")


# Task 23: What is the average alcohol content of the ingredients? (Without AVG() function.

c.execute('''
SELECT SUM(ingredient.alkoholgehalt) / COUNT (ingredient.alkoholgehalt)
FROM ingredient
''')
sum_count_ing= c.fetchall()
print(f"\nTask 23:\nThere average of alcohol content of the ingredients without using the AVG() function is {sum_count_ing[0][0]}.")
