'''
This python file will be used to answer the questions 
9 to 13 
made for the SQL Challenge,
the task will be presente as a comment and bellow its respective code,
the answer will be generated by running the code.
'''

from csv import list_dialects
from os import confstr_names
import sqlite3
from threading import local

conn = sqlite3.connect('cocktails_database.sqlite')
c = conn.cursor()

# Task 9: Create a MY_COCKTAILS table that has the same structure as COCKTAIL. 
# Insert the contents of table COCKTAIL into MY_COCKTAILS at the same time. 
# You execute all subsequent changes exclusively on MY_COCKTAILS.

c.execute('''
CREATE TABLE IF NOT EXISTS My_Cocktails AS
    SELECT cid, cname, alkoholisch, gid
    FROM cocktail
''')
#conn.commit()
print("\nTask 9:\nTable was created and added to the database.")

# Task 10: insert a new cocktail "Purple cow" in the table MY_COCKTAILS. 
# The cocktail is alcoholic, served in a snifter and has the ID 18.

c.execute('''DELETE FROM My_Cocktails WHERE My_Cocktails.cid = 18''')# so it doenst doubles again if the code is executed again.

c.execute('''
INSERT INTO My_Cocktails (cid, cname, alkoholisch, gid)
VALUES (18,'Purple cow', 'y', (
    SELECT glas.gid
    FROM glas
    WHERE glas.gname= 'Schwenker'))
''')
#conn.commit()     # this line is commented out since if executed again it would add this row again,
# since python is being used the IGNORE command does not work.
print("\nTask 10:\nNew row with new cocktail created in My_Cocktails.")

# Task 11: The cocktail "Purple Cow" is actually called "Blue Cow". Correct this mistake. 

c.execute('''
UPDATE My_Cocktails
SET cname = 'Blue Cow'
WHERE cname = 'Purple cow'
''')
print("\nTask 11:\nPurple Cow cocktail renamed to Blue Cow.")

#Task 12:  first create a table MY_INGREDIENT that has the same structure as INGREDIENT. 
# Let's assume that the alcohol content of all ingredients of the cocktail Knieweich is actually 
# twice as high as the entered value. Then correct this error in the MY_INGREDIENTS table.

c.execute('''
DROP TABLE My_Ingredient;
''') # so it doenst doubles again if the code is executed again.

c.execute('''
CREATE TABLE IF NOT EXISTS My_Ingredient AS
    SELECT zid, zname, alkoholgehalt
    FROM ingredient
''')

c.execute('''
UPDATE My_Ingredient
SET alkoholgehalt = alkoholgehalt * 2
WHERE zid IN (
    SELECT Ingredient_Cocktail.zid
    FROM Ingredient_Cocktail
    WHERE Ingredient_Cocktail.cid = (
        SELECT cocktail.cid
        FROM cocktail
        WHERE cocktail.cname='Knieweich'))
''')
print("\nTask 12:\nMy_Ingredient table created and Knieweich's ingredients alcohol content was corrected.")

# Task 13: Delete all cocktails from the MY_COCKTAILS table that contain "Campari" as an ingredient.

c.execute('''
DELETE 
FROM My_cocktails 
WHERE My_cocktails.cid IN (
    SELECT Ingredient_Cocktail.cid
    FROM Ingredient_Cocktail
    WHERE Ingredient_Cocktail.zid = (
        SELECT ingredient.zid
        FROM ingredient
        WHERE ingredient.zname='Campari'
    )
)
''')
print("\nTask 13:\nCocktails that contained the ingredient 'Campari' were deleted.")


conn.commit()
