'''
This python file will be used to answer the questions 
24 to 27
made for the SQL Challenge,
the task will be presente as a comment and bellow its respective code,
the answer will be generated by running the code.
'''

from csv import list_dialects
from os import confstr_names
import sqlite3
from threading import local

conn = sqlite3.connect('cocktails_database.sqlite')
c = conn.cursor()


# Task 24: A cocktail consists of several ingredients. 
# The number of units of each Ingredients per cocktail are listed in the table INGREDIENT_COCKTAIL.

#(a) The number of ingredients per cocktail.

c.execute('''
SELECT Cocktail.cname,
    COUNT(Ingredient_Cocktail.zid)
FROM Ingredient_Cocktail, Cocktail
WHERE Ingredient_Cocktail.cid = Cocktail.cid
GROUP BY Cocktail.cid
''')
ing_per_cocktail = c.fetchall()
print("Task 24:\nThis are the number of ingredients per cocktail:")
for i in ing_per_cocktail:
    if i[1] == 1:
        print(f"The cocktail {i[0]} has {i[1]} ingredient.")
    else: print(f"The cocktail {i[0]} has {i[1]} ingredients.")

#(b) The number of ingredients per cocktail is required, but only for cocktails with more than 2 ingredients.

c.execute('''
SELECT Cocktail.cname,
    COUNT(Ingredient_Cocktail.zid)
FROM Ingredient_Cocktail, Cocktail
WHERE Ingredient_Cocktail.cid = Cocktail.cid
GROUP BY Cocktail.cid
HAVING COUNT(*) > 2
''')
more_than_2_ing = c.fetchall()
print("\nTask 25:\nThis are the number of ingredients for the cocktails that require more than 2:")
for i in more_than_2_ing:
    print(f"The cocktail {i[0]} has {i[1]} ingredients.")

#(c) The sum of the units of measure of the respective ingredients per cocktail is sought.

c.execute('''
''')
x = c.fetchall()

#(d) The sum of the units of measure of the respective alcoholic ingredients per cocktail is sought.

c.execute('''
''')
x = c.fetchall()